# Generated by Django 3.0 on 2019-12-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1학기'), (2, '2학기'), (3, '3학기'), (4, '4학기')]),
        ),
    ]
