# Generated by Django 3.0 on 2019-12-17 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20191217_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open_dt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
