# Generated by Django 3.0 on 2019-12-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_course_open_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1학기'), (2, '2학기'), (3, '여름학기'), (4, '겨울학기')]),
        ),
    ]
