# Generated by Django 3.0 on 2019-12-17 02:15

from django.db import migrations, models
import lecture.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20191217_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(null=True, upload_to=lecture.models.notice_upload_path),
        ),
    ]
