# Generated by Django 3.0 on 2019-12-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_auto_20191217_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='attachment',
            new_name='file',
        ),
    ]
