# Generated by Django 3.0 on 2019-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_auto_20191217_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
