# Generated by Django 3.0 on 2019-12-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lecture.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0012_auto_20191217_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=lecture.models.notice_comment_upload_path)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Notice')),
                ('writer', models.ForeignKey(default='unknown user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
