# Generated by Django 3.0 on 2019-12-17 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_noticecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticecomment',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='pub_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
