# Generated by Django 3.0 on 2019-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=-1, max_length=100),
        ),
    ]
