# Generated by Django 3.0 on 2019-12-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191217_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, '학생'), (1, '교수')], default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
